name: lint

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
        
      - name: start-lint
        run: make lint